name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install aqtinstall
    
    - name: Install Qt
      shell: bash
      run: |
        # Install Qt
        python -m aqt install-qt ${{ runner.os }} desktop 6.5.0 wasm_32 -m qtwebengine
        
        # Add Qt to PATH
        if [ "${{ runner.os }}" = "macOS" ]; then
          echo "$HOME/Qt/6.5.0/wasm_32/bin" >> $GITHUB_PATH
        elif [ "${{ runner.os }}" = "Linux" ]; then
          echo "$HOME/Qt/6.5.0/wasm_32/bin" >> $GITHUB_PATH
          sudo apt-get update
          sudo apt-get install -y build-essential
        else  # Windows
          echo "C:\\Qt\\6.5.0\\wasm_32\\bin" >> $GITHUB_PATH
        fi
    
    - name: Configure and build
      shell: bash
      run: |
        mkdir -p build
        cd build
        cmake ../../qt_web_editor -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release

    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}
        path: build/
        retention-days: 1
