name: Build and Release Rapid

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-windows:
    name: Build and Release on Windows
    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt 6.5.3 using AQT
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          target: 'desktop'
          arch: win64_msvc2019_64
          modules: 'qtwebengine qtwebchannel qtpositioning qtwebsockets'

      - name: Install 7zip for packaging
        run: choco install -y 7zip

      - name: Configure CMake in build folder
        run: |
          mkdir build
          cd build
          cmake ../qt_web_editor -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$Env:Qt6_DIR"

      - name: Build project
        run: |
          cd build
          cmake --build . --config Release --parallel

      - name: Verify build output files
        run: |
          Write-Host "Files in build folder:"
          Get-ChildItem -Path build -Recurse | Format-Table -AutoSize

      - name: Verify Rapid.exe exists
        run: |
          if (-Not (Test-Path -Path build\Rapid.exe)) {
            Write-Error "ERROR: Rapid.exe not found in build folder! Build likely failed."
            exit 1
          } else {
            Write-Host "Rapid.exe found."
          }

      - name: Bundle Qt dependencies using windeployqt
        run: |
          & "$Env:Qt6_DIR\bin\windeployqt.exe" --release build\Rapid.exe

      - name: Package executable and resources into zip
        run: |
          cd build
          7z a Rapid-Windows.zip Rapid.exe resources/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rapid-windows
          path: build/Rapid-Windows.zip

      - name: Create GitHub Release asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/Rapid-Windows.zip
